namespace SINCRODEService.Models
{
    public partial class PersonasT
    {
        public int Id { get; set; }
        public int? IdPersona { get; set; }
        public string Dni { get; set; }
        public string Matricula { get; set; }
        public string Nombre { get; set; }
        public string Apellido1 { get; set; }
        public string Apellido2 { get; set; }
        public string Apellidos { get; set; }
        public string Fnacimiento { get; set; }
        public string Sexo { get; set; }
        public string EstadoCivil { get; set; }
        public int? NumHijos { get; set; }
        public string Cargo { get; set; }
        public string Categoria { get; set; }
        public string FechaAlta { get; set; }
        public string FechaBaja { get; set; }
        public string Nss { get; set; }
        public string UltRevision { get; set; }
        public string SigRevision { get; set; }
        public string Direccion { get; set; }
        public string Poblacion { get; set; }
        public string Provincia { get; set; }
        public string CodPostal { get; set; }
        public string Pais { get; set; }
        public string Extension { get; set; }
        public string Telefono { get; set; }
        public string Movil { get; set; }
        public string Email { get; set; }
        public string MatriculaCoche { get; set; }
        public string ModeloCoche { get; set; }
        public int? Plaza { get; set; }
        public string MatriculaCoche2 { get; set; }
        public string ModeloCoche2 { get; set; }
        public int? Plaza2 { get; set; }
        public string MatriculaCoche3 { get; set; }
        public string ModeloCoche3 { get; set; }
        public int? Plaza3 { get; set; }
        public string MatriculaCoche4 { get; set; }
        public string ModeloCoche4 { get; set; }
        public int? Plaza4 { get; set; }
        public string Observaciones { get; set; }
        public string Vip { get; set; }
        public string Contrata { get; set; }
        public string Pendiente { get; set; }
        public string RecibeVisitas { get; set; }
        public int? RegistroInicial { get; set; }
        public int? RegistroFinal { get; set; }
        public string Destino { get; set; }
        public string FechaExpedicion { get; set; }
        public string LugarNacimiento { get; set; }
        public string Nacionalidad { get; set; }
        public string UsuarioAd { get; set; }
        public int FkSede { get; set; }
        public int? FkTipoPersona { get; set; }
        public int? FkTipoContrato { get; set; }
        public int? FkEdificio { get; set; }
        public int? FkPlanta { get; set; }
        public int? FkZona { get; set; }
        public int? FkEmpresa { get; set; }
        public int? FkEmpresaContratada { get; set; }
        public int? FkEmpresaSubcontratada { get; set; }
        public int? FkCentro { get; set; }
        public int? FkDireccion { get; set; }
        public int? FkDepartamento { get; set; }
        public int? FkImagen { get; set; }
        public string DocumentosOk { get; set; }
        public string MatriculaCoche5 { get; set; }
        public string ModeloCoche5 { get; set; }
        public int? Plaza5 { get; set; }
        public int? FkImgFirma { get; set; }
        public int? FkImgDni1 { get; set; }
        public int? FkImgDni2 { get; set; }
        public string Autorizada { get; set; }
        public string CodigoPersona { get; set; }
        public int? IdObjetoGlobal { get; set; }
        public string ParametrosIntegracion { get; set; }
        public string MarcaCoche { get; set; }
        public string MarcaCoche2 { get; set; }
        public string MarcaCoche3 { get; set; }
        public string MarcaCoche4 { get; set; }
        public string MarcaCoche5 { get; set; }
        public string Edificio { get; set; }
        public string Planta { get; set; }
        public string Zona { get; set; }
        public string EstadoActual { get; set; }
        public string FechaInicioListaNegra { get; set; }
        public string FechaFinListaNegra { get; set; }
        public string UsuarioListaNegra { get; set; }
        public string PuestoListaNegra { get; set; }
        public string FechaListaNegra { get; set; }
        public string MotivoListaNegra { get; set; }
        public string Pass { get; set; }
        public int? FkPersonaAuxiliar { get; set; }
        public string ColorCoche { get; set; }
        public string ColorCoche2 { get; set; }
        public string ColorCoche3 { get; set; }
        public string ColorCoche4 { get; set; }
        public string ColorCoche5 { get; set; }
        public int? FkTipoVehiculo1 { get; set; }
        public int? FkTipoVehiculo2 { get; set; }
        public int? FkTipoVehiculo3 { get; set; }
        public int? FkTipoVehiculo4 { get; set; }
        public int? FkTipoVehiculo5 { get; set; }
        public int? ExternId { get; set; }
        public string PasarAnomina { get; set; }
        public int? FkSupervisor1 { get; set; }
        public int? FkSupervisor2 { get; set; }
        public int? FkSupervisor3 { get; set; }
        public string EsSupervisorPresencia { get; set; }
    }
}
