namespace SINCRODEService.Models
{
    public partial class Tarjetas
    {
        public int Id { get; set; }
        public double? Codigo { get; set; }
        public string CodTarjeta { get; set; }
        public string Matricula { get; set; }
        public string Matricula2 { get; set; }
        public string Matricula3 { get; set; }
        public string Matricula4 { get; set; }
        public string Matricula5 { get; set; }
        public int? Orden { get; set; }
        public string CodAlternativo { get; set; }
        public string Nip { get; set; }
        public string TipoTarjeta { get; set; }
        public string TarjetaRonda { get; set; }
        public string Estado { get; set; }
        public string FechaInicio { get; set; }
        public string FechaFin { get; set; }
        public string TarjetaEspecial { get; set; }
        public string TarjetaVehiculo { get; set; }
        public string OcultarMovimientos { get; set; }
        public string ArmadoDesarmado { get; set; }
        public string AccesoApista { get; set; }
        public string TarjetaPortatil { get; set; }
        public string ChequeoPestillo { get; set; }
        public string Aviso { get; set; }
        public string EnviarAviso { get; set; }
        public int? Plantilla { get; set; }
        public string UltimaImpresion { get; set; }
        public int? NumeroCopias { get; set; }
        public string Fhmovimiento { get; set; }
        public string ModoAccesoMatricula { get; set; }
        public string TarjetaAccesoParaVisita { get; set; }
        public string Provisional { get; set; }
        public string EnviarHuella { get; set; }
        public string BiestableAutonomos { get; set; }
        public int? FkEmbarque { get; set; }
        public int? FkTarjetaAsociada { get; set; }
        public int? FkRecinto { get; set; }
        public int? FkLector { get; set; }
        public int? FkHaccesos { get; set; }
        public int? FkCitaPrevia { get; set; }
        public int? FkPerfilVisita { get; set; }
        public int? FkPersonaActual { get; set; }
        public string BorradoPendiente { get; set; }
        public string Observaciones { get; set; }
        public string FechaEmision { get; set; }
        public int? FkEmpresa { get; set; }
        public string Herramienta { get; set; }
        public string Actualizada { get; set; }
        public int? IdTarjeta { get; set; }
        public string TarjetaVisitaPermanente { get; set; }
        public string ModoAccesoHuella { get; set; }
        public string HorarioLectoresDoc { get; set; }
        public string Grabada { get; set; }
        public string NoDocumentosOk { get; set; }
        public int? FkVehiculoActual { get; set; }
        public int? FkPlantilla { get; set; }
        public string ValidacionPorPasoLector { get; set; }
        public string FechaLectorValidacion { get; set; }
        public string CodTarjetaLargo { get; set; }
        public int? IdObjetoGlobal { get; set; }
        public string NoSincIntercentros { get; set; }
        public int? FkImagen { get; set; }
        public int? FkPersonaAcuse { get; set; }
        public int? FkPeriodoFecha { get; set; }
        public int? ContadorDeshabilitar { get; set; }
        public string Telefono { get; set; }
        public int? EstadoTarjetaDvc { get; set; }
        public string GuidRegistroDvc { get; set; }
        public int? TipoTecnologiaMobileAccess { get; set; }
        public int? ComidasDisponibles { get; set; }
        public string VipenComedor { get; set; }
        public string FechaCambioEstado { get; set; }
        public int? MotivoEstadoTarjeta { get; set; }
        public int? TipoTarjetaPersonalizado { get; set; }
    }
}
