//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SINCRODEService {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.0.0.0")]
    internal sealed partial class SincroDE : global::System.Configuration.ApplicationSettingsBase {
        
        private static SincroDE defaultInstance = ((SincroDE)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SincroDE())));
        
        public static SincroDE Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("server=localhost;database=DASSNET;uid=usuario;pwd=xxx\"")]
        public string DassnetAccess {
            get {
                return ((string)(this["DassnetAccess"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(" https://rutaevalos/")]
        public string EvalosAccess {
            get {
                return ((string)(this["EvalosAccess"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ftp://gentalia.ddns.net/SincronizadorDE/")]
        public string FTPLoga {
            get {
                return ((string)(this["FTPLoga"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\InOut")]
        public string RutaFileTemp {
            get {
                return ((string)(this["RutaFileTemp"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("server=localhost;database=SINCRODEDB;uid=usuario;pwd=xxx\"")]
        public string SQLConexion {
            get {
                return ((string)(this["SQLConexion"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12/11/2019 10:00:00")]
        public global::System.DateTime ExcetuteTime1 {
            get {
                return ((global::System.DateTime)(this["ExcetuteTime1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12/11/2019 14:00:00")]
        public global::System.DateTime ExcetuteTime2 {
            get {
                return ((global::System.DateTime)(this["ExcetuteTime2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12/11/2019 21:00:00")]
        public global::System.DateTime ExcetuteTime3 {
            get {
                return ((global::System.DateTime)(this["ExcetuteTime3"]));
            }
        }
    }
}
